---
- connection: local
  hosts: localhost
  sudo: true
  remote_user: douglas
  vars_files:
    - vault.yml
  vars:
    project: openvpn
  roles:
    - role: stevenharradine.pseudo-forge
    - role: stevenharradine.static-ip
      static_ip_address: "192.168.1.{% if environment_tier=='development' %}90{% elif environment_tier=='production' %}200{% endif %}"
    - role: stevenharradine.hostname
    - role: stevenharradine.openvpn
      openvpn_firewall_allow_ssh: yes
