---
- hosts: OpenVPN
  sudo: true
  remote_user: douglas
  vars:
    hostname: OpenVPN
  tasks:
  - name: change hostname
    hostname:
      name: "{{ hostname }}"

  - name: update hosts
    lineinfile:
      dest: /etc/hosts
      line: "127.0.1.1       {{ hostname }}"

  - name: install software | apt
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - openvpn
      - easy-rsa