---
- connection: local
  hosts: localhost
  sudo: true
  remote_user: douglas
  include_vars: vault.yml
  vars:
    project: openvpn
  roles:
    - role: stevenharradine.static-ip
      static_ip_address: "192.168.1.{% if environment_tier=='development' %}90{% elif environment_tier=='production' %}200{% endif %}"
    - role: stevenharradine.hostname
    - role: stevenharradine.openvpn
  tasks:
    - name: enable pseudo-forge
      lineinfile:
        dest: /home/douglas/.bashrc
        state: present
        line: "alias reforge='cd /home/douglas/playbook-{{ project }}/ && git pull && sudo ansible-galaxy install -r dependencies.yml --force && ansible-playbook playbook.yml -i hosts/{{ environment_tier }}'"
        insertafter: EOF
